[2025-08-02 22:20:09] [INFO] [main.py:53] - Запуск приложения: инициализация БД
[2025-08-02 22:20:09] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:20:09] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:20:09] [INFO] [main.py:55] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:20:09] [INFO] [main.py:73] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:22:59] [DEBUG] [main.py:139] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=8
[2025-08-02 22:22:59] [DEBUG] [main.py:156] - Сформирован список месяцев для выборки: [(2025, 7), (2025, 8)]
[2025-08-02 22:23:20] [DEBUG] [main.py:139] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:23:20] [DEBUG] [main.py:156] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:27:22] [INFO] [main.py:79] - Планировщик остановлен
[2025-08-02 22:28:07] [INFO] [main.py:54] - Запуск приложения: инициализация БД
[2025-08-02 22:28:07] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:28:07] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:28:07] [INFO] [main.py:56] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:28:07] [INFO] [main.py:74] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:28:26] [DEBUG] [main.py:140] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:28:26] [DEBUG] [main.py:157] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:29:26] [INFO] [main.py:80] - Планировщик остановлен
[2025-08-02 22:29:36] [INFO] [main.py:54] - Запуск приложения: инициализация БД
[2025-08-02 22:29:36] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:29:36] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:29:36] [INFO] [main.py:56] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:29:36] [INFO] [main.py:74] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:30:55] [DEBUG] [main.py:140] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:30:55] [DEBUG] [main.py:157] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:30:55] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-02 22:30:55] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-02 22:30:55] [DEBUG] [main.py:160] - Открыта сессия с базой данных
[2025-08-02 22:30:55] [ERROR] [main.py:170] - Ошибка при выполнении запроса к базе: name 'select' is not defined
Traceback (most recent call last):
  File "/app/main.py", line 163, in get_monthly_stats
    select(MonthlyStats).where(
    ^^^^^^
NameError: name 'select' is not defined. Did you forget to import 'select'?
[2025-08-02 22:30:55] [ERROR] [database.py:57] - Ошибка в контексте сессии: 500: Ошибка доступа к базе данных
[2025-08-02 22:30:55] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-02 22:31:03] [DEBUG] [main.py:140] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:31:03] [DEBUG] [main.py:157] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:31:03] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-02 22:31:03] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-02 22:31:03] [DEBUG] [main.py:160] - Открыта сессия с базой данных
[2025-08-02 22:31:03] [ERROR] [main.py:170] - Ошибка при выполнении запроса к базе: name 'select' is not defined
Traceback (most recent call last):
  File "/app/main.py", line 163, in get_monthly_stats
    select(MonthlyStats).where(
    ^^^^^^
NameError: name 'select' is not defined. Did you forget to import 'select'?
[2025-08-02 22:31:03] [ERROR] [database.py:57] - Ошибка в контексте сессии: 500: Ошибка доступа к базе данных
[2025-08-02 22:31:03] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-02 22:31:24] [INFO] [main.py:80] - Планировщик остановлен
[2025-08-02 22:32:35] [INFO] [main.py:55] - Запуск приложения: инициализация БД
[2025-08-02 22:32:35] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:32:35] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:32:35] [INFO] [main.py:57] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:32:35] [INFO] [main.py:75] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:33:30] [DEBUG] [main.py:141] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:33:30] [DEBUG] [main.py:158] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:33:30] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-02 22:33:30] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-02 22:33:30] [DEBUG] [main.py:161] - Открыта сессия с базой данных
[2025-08-02 22:33:30] [ERROR] [main.py:171] - Ошибка при выполнении запроса к базе: name 'tuple_' is not defined
Traceback (most recent call last):
  File "/app/main.py", line 165, in get_monthly_stats
    tuple_(MonthlyStats.year, MonthlyStats.month).in_(months)
    ^^^^^^
NameError: name 'tuple_' is not defined. Did you mean: 'tuple'?
[2025-08-02 22:33:30] [ERROR] [database.py:57] - Ошибка в контексте сессии: 500: Ошибка доступа к базе данных
[2025-08-02 22:33:30] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-02 22:34:12] [INFO] [main.py:81] - Планировщик остановлен
[2025-08-02 22:34:24] [INFO] [main.py:55] - Запуск приложения: инициализация БД
[2025-08-02 22:34:24] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:34:24] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:34:24] [INFO] [main.py:57] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:34:24] [INFO] [main.py:75] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:34:46] [DEBUG] [main.py:141] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:34:46] [DEBUG] [main.py:158] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:34:46] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-02 22:34:46] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-02 22:34:46] [DEBUG] [main.py:161] - Открыта сессия с базой данных
[2025-08-02 22:34:46] [DEBUG] [main.py:169] - Получено из базы 1 записей статистики
[2025-08-02 22:34:46] [DEBUG] [main.py:176] - Создана карта статистики по годам и месяцам
[2025-08-02 22:34:46] [ERROR] [database.py:57] - Ошибка в контексте сессии: name 'OrderedDict' is not defined
[2025-08-02 22:34:46] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-02 22:36:03] [INFO] [main.py:81] - Планировщик остановлен
[2025-08-02 22:36:13] [INFO] [main.py:56] - Запуск приложения: инициализация БД
[2025-08-02 22:36:13] [DEBUG] [database.py:34] - Начало инициализации базы данных...
[2025-08-02 22:36:13] [INFO] [database.py:38] - База данных успешно инициализирована.
[2025-08-02 22:36:13] [INFO] [main.py:58] - Приложение успешно запущено. Соединение с базой данных установлено.
[2025-08-02 22:36:13] [INFO] [main.py:76] - Планировщик запущен, задача будет выполняться каждые сутки
[2025-08-02 22:36:35] [DEBUG] [main.py:142] - Получен запрос /monthly_stats с параметрами: from_year=2025, from_month=7, to_year=2025, to_month=7
[2025-08-02 22:36:35] [DEBUG] [main.py:159] - Сформирован список месяцев для выборки: [(2025, 7)]
[2025-08-02 22:36:35] [INFO] [database.py:51] - Открытие сессии с БД...
[2025-08-02 22:36:35] [INFO] [database.py:54] - Сессия с БД успешно открыта.
[2025-08-02 22:36:35] [DEBUG] [main.py:162] - Открыта сессия с базой данных
[2025-08-02 22:36:35] [DEBUG] [main.py:170] - Получено из базы 1 записей статистики
[2025-08-02 22:36:35] [DEBUG] [main.py:177] - Создана карта статистики по годам и месяцам
[2025-08-02 22:36:35] [DEBUG] [main.py:184] - Добавляем данные за 2025-07: amount=5675.0, count=2, all_time_count=2
[2025-08-02 22:36:35] [INFO] [database.py:60] - Закрытие сессии с БД.
[2025-08-02 22:36:35] [INFO] [main.py:198] - Отправляем ответ с 1 месяцами статистики
[2025-08-02 22:37:17] [INFO] [main.py:82] - Планировщик остановлен
